version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./_build:/app/_build
    stdin_open: true
    tty: true

  web:
    extends: app
    ports:
      - 42069:42069
    expose:
      - 42069
    command: bash -c "while [ true ]; do sleep 10; done"
    environment:
      - MIX_ENV=dev
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_DBPORT=5532
      - PG_DBNAME=threefingers_dev
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5543:5543
    expose:
      - 5543

# tests:
#   extends: app
#   ports:
#     - 42269:42269
#   command: mix do deps.get, coveralls, credo --strict, format --check-formatted
#   environment:
#     - MIX_ENV=test
  #   - PG_USERNAME=postgres
  #   - PG_PASSWORD=postgres
  #   - PG_HOST=db
  #   - PG_DBPORT=5432
  #   - PG_DBNAME=threefingers_test
  # depends_on:
  #   - db
# networks:
#   default:
#   threefingers:
#     name: threefingers
