version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./_build:/app/_build
    stdin_open: true
    tty: true

  web:
    extends: app
    ports:
      - 4200:4200
    expose:
      - 4200
    # command: bash -c "while [ true ]; do sleep 10; done"
    environment:
      - MIX_ENV=dev
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_DBPORT=5420
      - PG_DBNAME=discuss_dev
      - PORT=4200
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5420:5420
    expose:
      - 5420

# tests:
#   extends: app
#   ports:
#     - 42269:42269
#   command: mix do deps.get, coveralls, credo --strict, format --check-formatted
#   environment:
#     - MIX_ENV=test
  #   - PG_USERNAME=postgres
  #   - PG_PASSWORD=postgres
  #   - PG_HOST=db
  #   - PG_DBPORT=5420
  #   - PG_DBNAME=discuss_test
  # depends_on:
  #   - db
# networks:
#   default:
#   discuss:
#     name: discuss
